# Site settings
title: DanteLiujie 博客
description: "个人技术博客"
url: "https://danteliujie.github.io/"

author:
  name: "DanteLiujie"
  email: "DanteLiujie@qq.com"
  url: "http://danteliujie.github.io"


# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
